# Generated by Django 3.0.6 on 2020-06-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio'},
        ),
    ]
