# Generated by Django 3.0.6 on 2020-06-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200611_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom_f']},
        ),
    ]
