# Generated by Django 3.0.6 on 2020-06-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200611_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null='False', upload_to='static'),
        ),
    ]
