# Generated by Django 3.0.6 on 2020-06-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200615_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'verbose_name': 'Fournisseur'},
        ),
    ]
