# Generated by Django 3.0.6 on 2020-06-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200615_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sous_categorie',
            options={'ordering': ['-nom_s_cat'], 'verbose_name': 'Sous-Categorie'},
        ),
    ]
