# Generated by Django 3.0.6 on 2020-07-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_remove_service_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fournisseurs',
            field=models.CharField(max_length=255, verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom Service'),
        ),
    ]
