# Generated by Django 3.0.6 on 2020-07-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20200713_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='nom_f',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom Fournisseur'),
        ),
    ]
