# Generated by Django 3.0.6 on 2020-07-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20200724_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='nom_f',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Nom Fournisseur'),
            preserve_default=False,
        ),
    ]
