# Generated by Django 3.0.6 on 2020-06-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Categorie')),
            ],
            options={
                'verbose_name': 'Sous-Categorie',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery')),
                ('fournisseur', models.CharField(max_length=255)),
                ('statut', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Categorie')),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Sous_Categorie')),
            ],
            options={
                'verbose_name': 'Servicios',
            },
        ),
    ]
