# Generated by Django 3.0.6 on 2020-06-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20200602_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null='False', upload_to='photos/'),
        ),
    ]
