# Generated by Django 3.0.6 on 2020-06-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_auto_20200610_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null='False', upload_to='gallery/'),
        ),
    ]
