# Generated by Django 3.0.6 on 2020-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_auto_20200610_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null='False', upload_to='static/img'),
        ),
    ]
