# Generated by Django 3.0.6 on 2020-06-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_auto_20200610_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null='False', upload_to='gallery/'),
        ),
    ]
