# Generated by Django 3.0.6 on 2020-06-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_auto_20200611_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null='False', upload_to='../gallery/'),
        ),
    ]
