# Generated by Django 3.0.6 on 2020-06-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0015_auto_20200611_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null='False', upload_to='gallery/'),
        ),
    ]
