# Generated by Django 3.0.6 on 2020-06-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0018_auto_20200611_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='nom_cat',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='fournisseur',
            new_name='fournisseurs',
        ),
        migrations.RenameField(
            model_name='sous_categorie',
            old_name='nom',
            new_name='nom_s_cat',
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_f', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/')),
                ('services', models.ManyToManyField(to='tool.Service')),
            ],
            options={
                'verbose_name': 'Fournisseur',
            },
        ),
    ]
