# Generated by Django 3.0.6 on 2020-06-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0025_auto_20200612_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
