# Generated by Django 3.0.6 on 2020-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0029_auto_20200615_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
