# Generated by Django 3.0.6 on 2020-06-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0031_auto_20200616_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom_cat',
            field=models.CharField(max_length=30, verbose_name=' Nom Categorie'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom_f',
            field=models.CharField(max_length=100, verbose_name='Nom Fournisseur'),
        ),
        migrations.AlterField(
            model_name='sous_categorie',
            name='nom_s_cat',
            field=models.CharField(max_length=100, verbose_name='Nom Souscategorie'),
        ),
    ]
