# Generated by Django 3.0.6 on 2020-06-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0032_auto_20200616_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom_cat',
            field=models.CharField(max_length=30, verbose_name='Nom Categorie'),
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='services',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.Service'),
        ),
    ]
