# Generated by Django 3.0.6 on 2020-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0034_auto_20200623_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='image',
            field=models.ImageField(null='False', upload_to='../static'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null='False', upload_to='../static'),
        ),
    ]
