# Generated by Django 3.0.6 on 2020-06-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0035_auto_20200625_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categorie',
        ),
    ]
