# Generated by Django 3.0.6 on 2020-07-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0037_typeelement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeElement',
        ),
    ]
