# Generated by Django 3.0.6 on 2020-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0039_typeelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('subTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title')),
                ('description', models.TextField(blank=True, max_length=30, null=True, verbose_name='Description')),
                ('order', models.IntegerField()),
                ('minRowWidth', models.IntegerField(default=1)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type of Element',
            },
        ),
    ]
