# Generated by Django 3.0.6 on 2020-07-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0040_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['-order'], 'verbose_name': 'Element'},
        ),
        migrations.AlterModelOptions(
            name='typeelement',
            options={'ordering': ['-order'], 'verbose_name': 'Type of Element'},
        ),
        migrations.AddField(
            model_name='element',
            name='color',
            field=models.CharField(default='white', max_length=10, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='element',
            name='typeElemnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.TypeElement'),
        ),
        migrations.AlterField(
            model_name='element',
            name='minRowWidth',
            field=models.IntegerField(default=1, verbose_name='Minimum Width'),
        ),
    ]
