# Generated by Django 3.0.6 on 2020-07-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0041_auto_20200703_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='typeElemnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.TypeElement'),
        ),
    ]
