# Generated by Django 3.0.6 on 2020-07-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0043_auto_20200703_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../static'),
        ),
    ]
