# Generated by Django 3.0.6 on 2020-07-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0044_element_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['-order'], 'verbose_name': 'Tree'},
        ),
        migrations.RemoveField(
            model_name='tree',
            name='element_father',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='is_root',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='root',
        ),
        migrations.AddField(
            model_name='tree',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.Element', verbose_name='Element'),
        ),
        migrations.AlterField(
            model_name='typeelement',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=30, null=True, verbose_name='Description')),
                ('color', models.CharField(max_length=10, null=True, verbose_name='Color')),
                ('rowWidth', models.IntegerField(default=1, verbose_name='Width')),
                ('order', models.IntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_children', to='tool.Element', verbose_name='Element')),
                ('element_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_fathers', to='tool.Element', verbose_name='Element')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.Node', verbose_name='Tree')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Tree', verbose_name='Tree')),
            ],
            options={
                'verbose_name': 'Tree',
                'ordering': ['-tree', '-element_father', '-order'],
            },
        ),
    ]
