# Generated by Django 3.0.6 on 2020-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0045_auto_20200704_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sous_categorie',
        ),
        migrations.RemoveField(
            model_name='sous_categorie',
            name='categorie',
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['-tree', '-element_father', '-order'], 'verbose_name': 'Node'},
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Sous_Categorie',
        ),
    ]
