# Generated by Django 3.0.6 on 2020-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0048_tree_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='in_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='in_home',
            field=models.BooleanField(default=False),
        ),
    ]
