# Generated by Django 3.0.6 on 2020-07-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_remove_service_categorie'),
        ('tool', '0051_auto_20200705_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Categorie'),
        ),
        migrations.AddField(
            model_name='element',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Service'),
        ),
        migrations.AddField(
            model_name='element',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Sous_Categorie'),
        ),
    ]
