# Generated by Django 3.0.6 on 2020-07-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_remove_service_categorie'),
        ('tool', '0052_auto_20200705_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Categorie'),
        ),
    ]
