# Generated by Django 3.0.6 on 2020-07-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_remove_service_categorie'),
        ('tool', '0053_tree_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Fournisseur'),
        ),
    ]
