# Generated by Django 3.0.6 on 2020-07-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0054_element_fournisseur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='in_visible',
            new_name='is_visible',
        ),
        migrations.AddField(
            model_name='node',
            name='subTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='node',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='node',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.Node', verbose_name='Father'),
        ),
        migrations.AlterField(
            model_name='node',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typeelement',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
