# Generated by Django 3.0.6 on 2020-07-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0056_node_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='linked',
            field=models.BooleanField(default=True),
        ),
    ]
