# Generated by Django 3.0.6 on 2021-02-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0058_auto_20200722_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['order'], 'verbose_name': 'Arbre'},
        ),
    ]
